name = "githubaction_example_for_julia"
uuid = "59d06fba-0cb0-4693-9d58-19b8a272ec5e"
authors = ["wakakusa"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
